ekf_filter_node:
  ros__parameters:
    frequency: 30.0  # 필터의 업데이트 빈도 (Hz)
    sensor_timeout: 0.1
    two_d_mode: true  # 2D 환경에서 사용 중이라면 true로 설정
    transform_time_offset: 0.0
    transform_timeout: 0.0
    publish_tf: true
    publish_acceleration: false
    map_frame: map  # 맵 프레임
    odom_frame: odom  # 오도메트리 프레임
    base_link_frame: base_link  # 로봇 본체 프레임
    world_frame: odom  # 세계 프레임

    odom0: /odom  # 휠 엔코더 데이터 토픽
    odom0_config: [true, true, false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom0_queue_size: 10
    odom0_nodelay: false
    odom0_differential: false
    odom0_relative: true

    imu0: /imu/data  # IMU 데이터 토픽
    imu0_config: [false, false, false,
                  true, true, false,
                  false, false, false,
                  false, false, true,
                  false, false, false]
    imu0_queue_size: 10
    imu0_nodelay: false
    imu0_remove_gravitational_acceleration: true

    use_control: false
    stamped_control: false
